export const PERMISSIONS_METADATA_KEY = Symbol("PERMISSIONS_METADATA_KEY");

export const REQUIRE_AUTH_METADATA_KEY = Symbol("REQUIRE_AUTH_METADATA_KEY");

export const AUTH_USER = Symbol("AUTH_USER");

export const AUTH_PERSONAL_ACCESS_TOKEN = Symbol("AUTH_PERSONAL_ACCESS_TOKEN");
