import { Type } from "@nestjs/common";

import { ConnectionInterface } from "../interfaces";

/**
 * Type alias for a Connection class type.
 *
 * This is used to reference Connection classes generated by ConnectionBuilder.build()
 * in type annotations for ConnectionManager.find() and similar methods.
 *
 * @typeParam T - The entity type for the connection
 *
 * @example
 * ```typescript
 * const UserConnection: ConnectionClass<User> = new ConnectionBuilder(User)
 *   .addField({ field: "name", type: "string" })
 *   .build().Connection;
 *
 * // Use in ConnectionManager
 * const result = await connectionManager.find(UserConnection, args);
 * ```
 */
export type ConnectionClass<T extends object> = Type<ConnectionInterface<T>>;
