export const TEST_QUEUE_NAME = "TEST_QUEUE_NAME";

export const TEST_REQUEST_SCOPED_QUEUE_NAME = "TEST_REQUEST_SCOPED_QUEUE_NAME";

export const QUEUE_NOT_FOUND_QUEUE_NAME = "QUEUE_NOT_FOUND_QUEUE_NAME";

export const TEST_JOB_NAME = "TEST_JOB_NAME";

export const TEST_BULK_JOB_NAME = "TEST_BULK_JOB_NAME";

export const TEST_REQUEST_SCOPED_JOB_NAME = "TEST_REQUEST_SCOPED_JOB_NAME";

export const TEST_JOB_DATA = { data: "test" };
