import type { PolicyDef } from "@mikro-orm/core";

/** Configuration for native user/workspace RLS policy factories. */
export interface ScopePolicyOptions {
  /** Database cast for the session identifier. Defaults to bigint. */
  type?: "bigint" | "integer" | "uuid" | "text";
  /** Entity property name, not a SQL column. Defaults to user or workspace. */
  property?: string;
  /** SQL operation granted by the policy. Defaults to all. */
  command?: PolicyDef["command"];
  /** Database roles receiving the grant. Defaults to ["authenticated"]. */
  roles?: string[];
  /** Optional policy name; omitted names are generated by MikroORM. */
  name?: string;
}
