/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as AuthenticatedLayoutRouteImport } from './app/_authenticated/layout'
import { Route as AuthLayoutRouteImport } from './app/auth/layout'
import { Route as AuthenticatedPageRouteImport } from './app/_authenticated/page'
import { Route as AuthenticatedUserLayoutRouteImport } from './app/_authenticated/user/layout'
import { Route as InvitePageRouteImport } from './app/invite/page'
import { Route as AuthenticatedWorkspacesPageRouteImport } from './app/_authenticated/workspaces/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdLayoutRouteImport } from './app/_authenticated/workspaces/$workspaceId/layout'
import { Route as AuthLoginPageRouteImport } from './app/auth/login/page'
import { Route as AuthenticatedUserApiKeysPageRouteImport } from './app/_authenticated/user/api-keys/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteImport } from './app/_authenticated/workspaces/$workspaceId/api-keys/layout'
import { Route as AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteImport } from './app/_authenticated/workspaces/$workspaceId/members/layout'
import { Route as AuthenticatedWorkspacesCreatePageRouteImport } from './app/_authenticated/workspaces/create/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdApiKeysPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/api-keys/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdMembersPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/members/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdSettingsPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/settings/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/members/$memberId/page'

const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPageRoute = AuthenticatedPageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)
const AuthenticatedUserLayoutRoute = AuthenticatedUserLayoutRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)
const InvitePageRoute = InvitePageRouteImport.update({
  id: '/invite/',
  path: '/invite/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspacesPageRoute =
  AuthenticatedWorkspacesPageRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdLayoutRoute =
  AuthenticatedWorkspacesWorkspaceIdLayoutRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthLoginPageRoute = AuthLoginPageRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthenticatedUserApiKeysPageRoute =
  AuthenticatedUserApiKeysPageRouteImport.update({
    id: '/api-keys/',
    path: '/api-keys/',
    getParentRoute: () => AuthenticatedUserLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdPageRoute =
  AuthenticatedWorkspacesWorkspaceIdPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute =
  AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute =
  AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AuthenticatedWorkspacesCreatePageRoute =
  AuthenticatedWorkspacesCreatePageRouteImport.update({
    id: '/workspaces/create/',
    path: '/workspaces/create/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute =
  AuthenticatedWorkspacesWorkspaceIdApiKeysPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdMembersPageRoute =
  AuthenticatedWorkspacesWorkspaceIdMembersPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute =
  AuthenticatedWorkspacesWorkspaceIdSettingsPageRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute =
  AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRouteImport.update({
    id: '/$memberId/',
    path: '/$memberId/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedPageRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/user': typeof AuthenticatedUserLayoutRouteWithChildren
  '/invite/': typeof InvitePageRoute
  '/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdLayoutRouteWithChildren
  '/workspaces/': typeof AuthenticatedWorkspacesPageRoute
  '/auth/login/': typeof AuthLoginPageRoute
  '/workspaces/$workspaceId/api-keys': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteWithChildren
  '/workspaces/$workspaceId/members': typeof AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteWithChildren
  '/user/api-keys/': typeof AuthenticatedUserApiKeysPageRoute
  '/workspaces/$workspaceId/': typeof AuthenticatedWorkspacesWorkspaceIdPageRoute
  '/workspaces/create/': typeof AuthenticatedWorkspacesCreatePageRoute
  '/workspaces/$workspaceId/api-keys/': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute
  '/workspaces/$workspaceId/members/': typeof AuthenticatedWorkspacesWorkspaceIdMembersPageRoute
  '/workspaces/$workspaceId/settings/': typeof AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute
  '/workspaces/$workspaceId/members/$memberId/': typeof AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthLayoutRouteWithChildren
  '/user': typeof AuthenticatedUserLayoutRouteWithChildren
  '/': typeof AuthenticatedPageRoute
  '/invite': typeof InvitePageRoute
  '/workspaces': typeof AuthenticatedWorkspacesPageRoute
  '/auth/login': typeof AuthLoginPageRoute
  '/user/api-keys': typeof AuthenticatedUserApiKeysPageRoute
  '/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdPageRoute
  '/workspaces/create': typeof AuthenticatedWorkspacesCreatePageRoute
  '/workspaces/$workspaceId/api-keys': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute
  '/workspaces/$workspaceId/members': typeof AuthenticatedWorkspacesWorkspaceIdMembersPageRoute
  '/workspaces/$workspaceId/settings': typeof AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute
  '/workspaces/$workspaceId/members/$memberId': typeof AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/_authenticated/user': typeof AuthenticatedUserLayoutRouteWithChildren
  '/_authenticated/': typeof AuthenticatedPageRoute
  '/invite/': typeof InvitePageRoute
  '/_authenticated/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdLayoutRouteWithChildren
  '/_authenticated/workspaces/': typeof AuthenticatedWorkspacesPageRoute
  '/auth/login/': typeof AuthLoginPageRoute
  '/_authenticated/workspaces/$workspaceId/api-keys': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/members': typeof AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteWithChildren
  '/_authenticated/user/api-keys/': typeof AuthenticatedUserApiKeysPageRoute
  '/_authenticated/workspaces/$workspaceId/': typeof AuthenticatedWorkspacesWorkspaceIdPageRoute
  '/_authenticated/workspaces/create/': typeof AuthenticatedWorkspacesCreatePageRoute
  '/_authenticated/workspaces/$workspaceId/api-keys/': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute
  '/_authenticated/workspaces/$workspaceId/members/': typeof AuthenticatedWorkspacesWorkspaceIdMembersPageRoute
  '/_authenticated/workspaces/$workspaceId/settings/': typeof AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute
  '/_authenticated/workspaces/$workspaceId/members/$memberId/': typeof AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/user'
    | '/invite/'
    | '/workspaces/$workspaceId'
    | '/workspaces/'
    | '/auth/login/'
    | '/workspaces/$workspaceId/api-keys'
    | '/workspaces/$workspaceId/members'
    | '/user/api-keys/'
    | '/workspaces/$workspaceId/'
    | '/workspaces/create/'
    | '/workspaces/$workspaceId/api-keys/'
    | '/workspaces/$workspaceId/members/'
    | '/workspaces/$workspaceId/settings/'
    | '/workspaces/$workspaceId/members/$memberId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/user'
    | '/'
    | '/invite'
    | '/workspaces'
    | '/auth/login'
    | '/user/api-keys'
    | '/workspaces/$workspaceId'
    | '/workspaces/create'
    | '/workspaces/$workspaceId/api-keys'
    | '/workspaces/$workspaceId/members'
    | '/workspaces/$workspaceId/settings'
    | '/workspaces/$workspaceId/members/$memberId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/user'
    | '/_authenticated/'
    | '/invite/'
    | '/_authenticated/workspaces/$workspaceId'
    | '/_authenticated/workspaces/'
    | '/auth/login/'
    | '/_authenticated/workspaces/$workspaceId/api-keys'
    | '/_authenticated/workspaces/$workspaceId/members'
    | '/_authenticated/user/api-keys/'
    | '/_authenticated/workspaces/$workspaceId/'
    | '/_authenticated/workspaces/create/'
    | '/_authenticated/workspaces/$workspaceId/api-keys/'
    | '/_authenticated/workspaces/$workspaceId/members/'
    | '/_authenticated/workspaces/$workspaceId/settings/'
    | '/_authenticated/workspaces/$workspaceId/members/$memberId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  InvitePageRoute: typeof InvitePageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedPageRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/user': {
      id: '/_authenticated/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AuthenticatedUserLayoutRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/invite/': {
      id: '/invite/'
      path: '/invite'
      fullPath: '/invite/'
      preLoaderRoute: typeof InvitePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspaces/': {
      id: '/_authenticated/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AuthenticatedWorkspacesPageRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId': {
      id: '/_authenticated/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginPageRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authenticated/user/api-keys/': {
      id: '/_authenticated/user/api-keys/'
      path: '/api-keys'
      fullPath: '/user/api-keys/'
      preLoaderRoute: typeof AuthenticatedUserApiKeysPageRouteImport
      parentRoute: typeof AuthenticatedUserLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/': {
      id: '/_authenticated/workspaces/$workspaceId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/api-keys': {
      id: '/_authenticated/workspaces/$workspaceId/api-keys'
      path: '/api-keys'
      fullPath: '/workspaces/$workspaceId/api-keys'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/members': {
      id: '/_authenticated/workspaces/$workspaceId/members'
      path: '/members'
      fullPath: '/workspaces/$workspaceId/members'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRoute
    }
    '/_authenticated/workspaces/create/': {
      id: '/_authenticated/workspaces/create/'
      path: '/workspaces/create'
      fullPath: '/workspaces/create/'
      preLoaderRoute: typeof AuthenticatedWorkspacesCreatePageRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/api-keys/': {
      id: '/_authenticated/workspaces/$workspaceId/api-keys/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/api-keys/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/members/': {
      id: '/_authenticated/workspaces/$workspaceId/members/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/members/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/settings/': {
      id: '/_authenticated/workspaces/$workspaceId/settings/'
      path: '/settings'
      fullPath: '/workspaces/$workspaceId/settings/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdSettingsPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/members/$memberId/': {
      id: '/_authenticated/workspaces/$workspaceId/members/$memberId/'
      path: '/$memberId'
      fullPath: '/workspaces/$workspaceId/members/$memberId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute
    }
  }
}

interface AuthenticatedUserLayoutRouteChildren {
  AuthenticatedUserApiKeysPageRoute: typeof AuthenticatedUserApiKeysPageRoute
}

const AuthenticatedUserLayoutRouteChildren: AuthenticatedUserLayoutRouteChildren =
  {
    AuthenticatedUserApiKeysPageRoute: AuthenticatedUserApiKeysPageRoute,
  }

const AuthenticatedUserLayoutRouteWithChildren =
  AuthenticatedUserLayoutRoute._addFileChildren(
    AuthenticatedUserLayoutRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute
}

const AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute:
      AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdMembersPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersPageRoute
  AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute
}

const AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdMembersPageRoute:
      AuthenticatedWorkspacesWorkspaceIdMembersPageRoute,
    AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute:
      AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdLayoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdPageRoute
  AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute
}

const AuthenticatedWorkspacesWorkspaceIdLayoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdLayoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute:
      AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute:
      AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdPageRoute:
      AuthenticatedWorkspacesWorkspaceIdPageRoute,
    AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute:
      AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdLayoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdLayoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdLayoutRouteChildren,
  )

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedUserLayoutRoute: typeof AuthenticatedUserLayoutRouteWithChildren
  AuthenticatedPageRoute: typeof AuthenticatedPageRoute
  AuthenticatedWorkspacesWorkspaceIdLayoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRouteWithChildren
  AuthenticatedWorkspacesPageRoute: typeof AuthenticatedWorkspacesPageRoute
  AuthenticatedWorkspacesCreatePageRoute: typeof AuthenticatedWorkspacesCreatePageRoute
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedUserLayoutRoute: AuthenticatedUserLayoutRouteWithChildren,
  AuthenticatedPageRoute: AuthenticatedPageRoute,
  AuthenticatedWorkspacesWorkspaceIdLayoutRoute:
    AuthenticatedWorkspacesWorkspaceIdLayoutRouteWithChildren,
  AuthenticatedWorkspacesPageRoute: AuthenticatedWorkspacesPageRoute,
  AuthenticatedWorkspacesCreatePageRoute:
    AuthenticatedWorkspacesCreatePageRoute,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

interface AuthLayoutRouteChildren {
  AuthLoginPageRoute: typeof AuthLoginPageRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLoginPageRoute: AuthLoginPageRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  InvitePageRoute: InvitePageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
