/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as AuthenticatedLayoutRouteImport } from './app/_authenticated/layout'
import { Route as AuthLayoutRouteImport } from './app/auth/layout'
import { Route as AuthenticatedPageRouteImport } from './app/_authenticated/page'
import { Route as AuthenticatedAdminLayoutRouteImport } from './app/_authenticated/admin/layout'
import { Route as AuthenticatedUserLayoutRouteImport } from './app/_authenticated/user/layout'
import { Route as InvitePageRouteImport } from './app/invite/page'
import { Route as AuthenticatedAdminPageRouteImport } from './app/_authenticated/admin/page'
import { Route as AuthenticatedAdminUsersLayoutRouteImport } from './app/_authenticated/admin/users/layout'
import { Route as AuthenticatedUserPageRouteImport } from './app/_authenticated/user/page'
import { Route as AuthenticatedUserApiKeysLayoutRouteImport } from './app/_authenticated/user/api-keys/layout'
import { Route as AuthenticatedWorkspacesPageRouteImport } from './app/_authenticated/workspaces/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdLayoutRouteImport } from './app/_authenticated/workspaces/$workspaceId/layout'
import { Route as AuthForgotPasswordPageRouteImport } from './app/auth/forgot-password/page'
import { Route as AuthLoginPageRouteImport } from './app/auth/login/page'
import { Route as AuthRegisterPageRouteImport } from './app/auth/register/page'
import { Route as AuthResetPasswordPageRouteImport } from './app/auth/reset-password/page'
import { Route as AuthVerifyEmailPageRouteImport } from './app/auth/verify-email/page'
import { Route as AuthenticatedAdminUsersPageRouteImport } from './app/_authenticated/admin/users/page'
import { Route as AuthenticatedUserApiKeysPageRouteImport } from './app/_authenticated/user/api-keys/page'
import { Route as AuthenticatedUserSecurityPageRouteImport } from './app/_authenticated/user/security/page'
import { Route as AuthenticatedUserWorkspacesPageRouteImport } from './app/_authenticated/user/workspaces/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteImport } from './app/_authenticated/workspaces/$workspaceId/api-keys/layout'
import { Route as AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteImport } from './app/_authenticated/workspaces/$workspaceId/members/layout'
import { Route as AuthenticatedWorkspacesCreatePageRouteImport } from './app/_authenticated/workspaces/create/page'
import { Route as AuthenticatedAdminUsersUserIdPageRouteImport } from './app/_authenticated/admin/users/$userId/page'
import { Route as AuthenticatedAdminUsersCreatePageRouteImport } from './app/_authenticated/admin/users/create/page'
import { Route as AuthenticatedUserApiKeysApiKeyIdPageRouteImport } from './app/_authenticated/user/api-keys/$apiKeyId/page'
import { Route as AuthenticatedUserApiKeysCreatePageRouteImport } from './app/_authenticated/user/api-keys/create/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdApiKeysPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/api-keys/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdMembersPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/members/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdSettingsPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/settings/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdApiKeysApiKeyIdPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/api-keys/$apiKeyId/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdApiKeysCreatePageRouteImport } from './app/_authenticated/workspaces/$workspaceId/api-keys/create/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRouteImport } from './app/_authenticated/workspaces/$workspaceId/members/$memberId/page'
import { Route as AuthenticatedWorkspacesWorkspaceIdMembersInvitePageRouteImport } from './app/_authenticated/workspaces/$workspaceId/members/invite/page'

const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPageRoute = AuthenticatedPageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)
const AuthenticatedAdminLayoutRoute =
  AuthenticatedAdminLayoutRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedUserLayoutRoute = AuthenticatedUserLayoutRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)
const InvitePageRoute = InvitePageRouteImport.update({
  id: '/invite/',
  path: '/invite/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminPageRoute = AuthenticatedAdminPageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminLayoutRoute,
} as any)
const AuthenticatedAdminUsersLayoutRoute =
  AuthenticatedAdminUsersLayoutRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedAdminLayoutRoute,
  } as any)
const AuthenticatedUserPageRoute = AuthenticatedUserPageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedUserLayoutRoute,
} as any)
const AuthenticatedUserApiKeysLayoutRoute =
  AuthenticatedUserApiKeysLayoutRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedUserLayoutRoute,
  } as any)
const AuthenticatedWorkspacesPageRoute =
  AuthenticatedWorkspacesPageRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdLayoutRoute =
  AuthenticatedWorkspacesWorkspaceIdLayoutRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthForgotPasswordPageRoute = AuthForgotPasswordPageRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLoginPageRoute = AuthLoginPageRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthRegisterPageRoute = AuthRegisterPageRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthResetPasswordPageRoute = AuthResetPasswordPageRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthVerifyEmailPageRoute = AuthVerifyEmailPageRouteImport.update({
  id: '/verify-email/',
  path: '/verify-email/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthenticatedAdminUsersPageRoute =
  AuthenticatedAdminUsersPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminUsersLayoutRoute,
  } as any)
const AuthenticatedUserApiKeysPageRoute =
  AuthenticatedUserApiKeysPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedUserApiKeysLayoutRoute,
  } as any)
const AuthenticatedUserSecurityPageRoute =
  AuthenticatedUserSecurityPageRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => AuthenticatedUserLayoutRoute,
  } as any)
const AuthenticatedUserWorkspacesPageRoute =
  AuthenticatedUserWorkspacesPageRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AuthenticatedUserLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdPageRoute =
  AuthenticatedWorkspacesWorkspaceIdPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute =
  AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute =
  AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AuthenticatedWorkspacesCreatePageRoute =
  AuthenticatedWorkspacesCreatePageRouteImport.update({
    id: '/workspaces/create/',
    path: '/workspaces/create/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedAdminUsersUserIdPageRoute =
  AuthenticatedAdminUsersUserIdPageRouteImport.update({
    id: '/$userId/',
    path: '/$userId/',
    getParentRoute: () => AuthenticatedAdminUsersLayoutRoute,
  } as any)
const AuthenticatedAdminUsersCreatePageRoute =
  AuthenticatedAdminUsersCreatePageRouteImport.update({
    id: '/create/',
    path: '/create/',
    getParentRoute: () => AuthenticatedAdminUsersLayoutRoute,
  } as any)
const AuthenticatedUserApiKeysApiKeyIdPageRoute =
  AuthenticatedUserApiKeysApiKeyIdPageRouteImport.update({
    id: '/$apiKeyId/',
    path: '/$apiKeyId/',
    getParentRoute: () => AuthenticatedUserApiKeysLayoutRoute,
  } as any)
const AuthenticatedUserApiKeysCreatePageRoute =
  AuthenticatedUserApiKeysCreatePageRouteImport.update({
    id: '/create/',
    path: '/create/',
    getParentRoute: () => AuthenticatedUserApiKeysLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute =
  AuthenticatedWorkspacesWorkspaceIdApiKeysPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdMembersPageRoute =
  AuthenticatedWorkspacesWorkspaceIdMembersPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute =
  AuthenticatedWorkspacesWorkspaceIdSettingsPageRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdApiKeysApiKeyIdPageRoute =
  AuthenticatedWorkspacesWorkspaceIdApiKeysApiKeyIdPageRouteImport.update({
    id: '/$apiKeyId/',
    path: '/$apiKeyId/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdApiKeysCreatePageRoute =
  AuthenticatedWorkspacesWorkspaceIdApiKeysCreatePageRouteImport.update({
    id: '/create/',
    path: '/create/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute =
  AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRouteImport.update({
    id: '/$memberId/',
    path: '/$memberId/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdMembersInvitePageRoute =
  AuthenticatedWorkspacesWorkspaceIdMembersInvitePageRouteImport.update({
    id: '/invite/',
    path: '/invite/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedPageRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/admin': typeof AuthenticatedAdminLayoutRouteWithChildren
  '/user': typeof AuthenticatedUserLayoutRouteWithChildren
  '/invite/': typeof InvitePageRoute
  '/admin/users': typeof AuthenticatedAdminUsersLayoutRouteWithChildren
  '/user/api-keys': typeof AuthenticatedUserApiKeysLayoutRouteWithChildren
  '/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdLayoutRouteWithChildren
  '/admin/': typeof AuthenticatedAdminPageRoute
  '/user/': typeof AuthenticatedUserPageRoute
  '/workspaces/': typeof AuthenticatedWorkspacesPageRoute
  '/auth/forgot-password/': typeof AuthForgotPasswordPageRoute
  '/auth/login/': typeof AuthLoginPageRoute
  '/auth/register/': typeof AuthRegisterPageRoute
  '/auth/reset-password/': typeof AuthResetPasswordPageRoute
  '/auth/verify-email/': typeof AuthVerifyEmailPageRoute
  '/workspaces/$workspaceId/api-keys': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteWithChildren
  '/workspaces/$workspaceId/members': typeof AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteWithChildren
  '/admin/users/': typeof AuthenticatedAdminUsersPageRoute
  '/user/api-keys/': typeof AuthenticatedUserApiKeysPageRoute
  '/user/security/': typeof AuthenticatedUserSecurityPageRoute
  '/user/workspaces/': typeof AuthenticatedUserWorkspacesPageRoute
  '/workspaces/$workspaceId/': typeof AuthenticatedWorkspacesWorkspaceIdPageRoute
  '/workspaces/create/': typeof AuthenticatedWorkspacesCreatePageRoute
  '/admin/users/$userId/': typeof AuthenticatedAdminUsersUserIdPageRoute
  '/admin/users/create/': typeof AuthenticatedAdminUsersCreatePageRoute
  '/user/api-keys/$apiKeyId/': typeof AuthenticatedUserApiKeysApiKeyIdPageRoute
  '/user/api-keys/create/': typeof AuthenticatedUserApiKeysCreatePageRoute
  '/workspaces/$workspaceId/api-keys/': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute
  '/workspaces/$workspaceId/members/': typeof AuthenticatedWorkspacesWorkspaceIdMembersPageRoute
  '/workspaces/$workspaceId/settings/': typeof AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute
  '/workspaces/$workspaceId/api-keys/$apiKeyId/': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysApiKeyIdPageRoute
  '/workspaces/$workspaceId/api-keys/create/': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysCreatePageRoute
  '/workspaces/$workspaceId/members/$memberId/': typeof AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute
  '/workspaces/$workspaceId/members/invite/': typeof AuthenticatedWorkspacesWorkspaceIdMembersInvitePageRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthLayoutRouteWithChildren
  '/': typeof AuthenticatedPageRoute
  '/invite': typeof InvitePageRoute
  '/admin': typeof AuthenticatedAdminPageRoute
  '/user': typeof AuthenticatedUserPageRoute
  '/workspaces': typeof AuthenticatedWorkspacesPageRoute
  '/auth/forgot-password': typeof AuthForgotPasswordPageRoute
  '/auth/login': typeof AuthLoginPageRoute
  '/auth/register': typeof AuthRegisterPageRoute
  '/auth/reset-password': typeof AuthResetPasswordPageRoute
  '/auth/verify-email': typeof AuthVerifyEmailPageRoute
  '/admin/users': typeof AuthenticatedAdminUsersPageRoute
  '/user/api-keys': typeof AuthenticatedUserApiKeysPageRoute
  '/user/security': typeof AuthenticatedUserSecurityPageRoute
  '/user/workspaces': typeof AuthenticatedUserWorkspacesPageRoute
  '/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdPageRoute
  '/workspaces/create': typeof AuthenticatedWorkspacesCreatePageRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdPageRoute
  '/admin/users/create': typeof AuthenticatedAdminUsersCreatePageRoute
  '/user/api-keys/$apiKeyId': typeof AuthenticatedUserApiKeysApiKeyIdPageRoute
  '/user/api-keys/create': typeof AuthenticatedUserApiKeysCreatePageRoute
  '/workspaces/$workspaceId/api-keys': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute
  '/workspaces/$workspaceId/members': typeof AuthenticatedWorkspacesWorkspaceIdMembersPageRoute
  '/workspaces/$workspaceId/settings': typeof AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute
  '/workspaces/$workspaceId/api-keys/$apiKeyId': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysApiKeyIdPageRoute
  '/workspaces/$workspaceId/api-keys/create': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysCreatePageRoute
  '/workspaces/$workspaceId/members/$memberId': typeof AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute
  '/workspaces/$workspaceId/members/invite': typeof AuthenticatedWorkspacesWorkspaceIdMembersInvitePageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminLayoutRouteWithChildren
  '/_authenticated/user': typeof AuthenticatedUserLayoutRouteWithChildren
  '/_authenticated/': typeof AuthenticatedPageRoute
  '/invite/': typeof InvitePageRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersLayoutRouteWithChildren
  '/_authenticated/user/api-keys': typeof AuthenticatedUserApiKeysLayoutRouteWithChildren
  '/_authenticated/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdLayoutRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminPageRoute
  '/_authenticated/user/': typeof AuthenticatedUserPageRoute
  '/_authenticated/workspaces/': typeof AuthenticatedWorkspacesPageRoute
  '/auth/forgot-password/': typeof AuthForgotPasswordPageRoute
  '/auth/login/': typeof AuthLoginPageRoute
  '/auth/register/': typeof AuthRegisterPageRoute
  '/auth/reset-password/': typeof AuthResetPasswordPageRoute
  '/auth/verify-email/': typeof AuthVerifyEmailPageRoute
  '/_authenticated/workspaces/$workspaceId/api-keys': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteWithChildren
  '/_authenticated/workspaces/$workspaceId/members': typeof AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteWithChildren
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersPageRoute
  '/_authenticated/user/api-keys/': typeof AuthenticatedUserApiKeysPageRoute
  '/_authenticated/user/security/': typeof AuthenticatedUserSecurityPageRoute
  '/_authenticated/user/workspaces/': typeof AuthenticatedUserWorkspacesPageRoute
  '/_authenticated/workspaces/$workspaceId/': typeof AuthenticatedWorkspacesWorkspaceIdPageRoute
  '/_authenticated/workspaces/create/': typeof AuthenticatedWorkspacesCreatePageRoute
  '/_authenticated/admin/users/$userId/': typeof AuthenticatedAdminUsersUserIdPageRoute
  '/_authenticated/admin/users/create/': typeof AuthenticatedAdminUsersCreatePageRoute
  '/_authenticated/user/api-keys/$apiKeyId/': typeof AuthenticatedUserApiKeysApiKeyIdPageRoute
  '/_authenticated/user/api-keys/create/': typeof AuthenticatedUserApiKeysCreatePageRoute
  '/_authenticated/workspaces/$workspaceId/api-keys/': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute
  '/_authenticated/workspaces/$workspaceId/members/': typeof AuthenticatedWorkspacesWorkspaceIdMembersPageRoute
  '/_authenticated/workspaces/$workspaceId/settings/': typeof AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute
  '/_authenticated/workspaces/$workspaceId/api-keys/$apiKeyId/': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysApiKeyIdPageRoute
  '/_authenticated/workspaces/$workspaceId/api-keys/create/': typeof AuthenticatedWorkspacesWorkspaceIdApiKeysCreatePageRoute
  '/_authenticated/workspaces/$workspaceId/members/$memberId/': typeof AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute
  '/_authenticated/workspaces/$workspaceId/members/invite/': typeof AuthenticatedWorkspacesWorkspaceIdMembersInvitePageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/user'
    | '/invite/'
    | '/admin/users'
    | '/user/api-keys'
    | '/workspaces/$workspaceId'
    | '/admin/'
    | '/user/'
    | '/workspaces/'
    | '/auth/forgot-password/'
    | '/auth/login/'
    | '/auth/register/'
    | '/auth/reset-password/'
    | '/auth/verify-email/'
    | '/workspaces/$workspaceId/api-keys'
    | '/workspaces/$workspaceId/members'
    | '/admin/users/'
    | '/user/api-keys/'
    | '/user/security/'
    | '/user/workspaces/'
    | '/workspaces/$workspaceId/'
    | '/workspaces/create/'
    | '/admin/users/$userId/'
    | '/admin/users/create/'
    | '/user/api-keys/$apiKeyId/'
    | '/user/api-keys/create/'
    | '/workspaces/$workspaceId/api-keys/'
    | '/workspaces/$workspaceId/members/'
    | '/workspaces/$workspaceId/settings/'
    | '/workspaces/$workspaceId/api-keys/$apiKeyId/'
    | '/workspaces/$workspaceId/api-keys/create/'
    | '/workspaces/$workspaceId/members/$memberId/'
    | '/workspaces/$workspaceId/members/invite/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/invite'
    | '/admin'
    | '/user'
    | '/workspaces'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/admin/users'
    | '/user/api-keys'
    | '/user/security'
    | '/user/workspaces'
    | '/workspaces/$workspaceId'
    | '/workspaces/create'
    | '/admin/users/$userId'
    | '/admin/users/create'
    | '/user/api-keys/$apiKeyId'
    | '/user/api-keys/create'
    | '/workspaces/$workspaceId/api-keys'
    | '/workspaces/$workspaceId/members'
    | '/workspaces/$workspaceId/settings'
    | '/workspaces/$workspaceId/api-keys/$apiKeyId'
    | '/workspaces/$workspaceId/api-keys/create'
    | '/workspaces/$workspaceId/members/$memberId'
    | '/workspaces/$workspaceId/members/invite'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/user'
    | '/_authenticated/'
    | '/invite/'
    | '/_authenticated/admin/users'
    | '/_authenticated/user/api-keys'
    | '/_authenticated/workspaces/$workspaceId'
    | '/_authenticated/admin/'
    | '/_authenticated/user/'
    | '/_authenticated/workspaces/'
    | '/auth/forgot-password/'
    | '/auth/login/'
    | '/auth/register/'
    | '/auth/reset-password/'
    | '/auth/verify-email/'
    | '/_authenticated/workspaces/$workspaceId/api-keys'
    | '/_authenticated/workspaces/$workspaceId/members'
    | '/_authenticated/admin/users/'
    | '/_authenticated/user/api-keys/'
    | '/_authenticated/user/security/'
    | '/_authenticated/user/workspaces/'
    | '/_authenticated/workspaces/$workspaceId/'
    | '/_authenticated/workspaces/create/'
    | '/_authenticated/admin/users/$userId/'
    | '/_authenticated/admin/users/create/'
    | '/_authenticated/user/api-keys/$apiKeyId/'
    | '/_authenticated/user/api-keys/create/'
    | '/_authenticated/workspaces/$workspaceId/api-keys/'
    | '/_authenticated/workspaces/$workspaceId/members/'
    | '/_authenticated/workspaces/$workspaceId/settings/'
    | '/_authenticated/workspaces/$workspaceId/api-keys/$apiKeyId/'
    | '/_authenticated/workspaces/$workspaceId/api-keys/create/'
    | '/_authenticated/workspaces/$workspaceId/members/$memberId/'
    | '/_authenticated/workspaces/$workspaceId/members/invite/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  InvitePageRoute: typeof InvitePageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedPageRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminLayoutRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/user': {
      id: '/_authenticated/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AuthenticatedUserLayoutRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/invite/': {
      id: '/invite/'
      path: '/invite'
      fullPath: '/invite/'
      preLoaderRoute: typeof InvitePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminPageRouteImport
      parentRoute: typeof AuthenticatedAdminLayoutRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersLayoutRouteImport
      parentRoute: typeof AuthenticatedAdminLayoutRoute
    }
    '/_authenticated/user/': {
      id: '/_authenticated/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof AuthenticatedUserPageRouteImport
      parentRoute: typeof AuthenticatedUserLayoutRoute
    }
    '/_authenticated/user/api-keys': {
      id: '/_authenticated/user/api-keys'
      path: '/api-keys'
      fullPath: '/user/api-keys'
      preLoaderRoute: typeof AuthenticatedUserApiKeysLayoutRouteImport
      parentRoute: typeof AuthenticatedUserLayoutRoute
    }
    '/_authenticated/workspaces/': {
      id: '/_authenticated/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AuthenticatedWorkspacesPageRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId': {
      id: '/_authenticated/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/auth/forgot-password/': {
      id: '/auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password/'
      preLoaderRoute: typeof AuthForgotPasswordPageRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginPageRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AuthRegisterPageRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/reset-password'
      fullPath: '/auth/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordPageRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/verify-email/': {
      id: '/auth/verify-email/'
      path: '/verify-email'
      fullPath: '/auth/verify-email/'
      preLoaderRoute: typeof AuthVerifyEmailPageRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersPageRouteImport
      parentRoute: typeof AuthenticatedAdminUsersLayoutRoute
    }
    '/_authenticated/user/api-keys/': {
      id: '/_authenticated/user/api-keys/'
      path: '/'
      fullPath: '/user/api-keys/'
      preLoaderRoute: typeof AuthenticatedUserApiKeysPageRouteImport
      parentRoute: typeof AuthenticatedUserApiKeysLayoutRoute
    }
    '/_authenticated/user/security/': {
      id: '/_authenticated/user/security/'
      path: '/security'
      fullPath: '/user/security/'
      preLoaderRoute: typeof AuthenticatedUserSecurityPageRouteImport
      parentRoute: typeof AuthenticatedUserLayoutRoute
    }
    '/_authenticated/user/workspaces/': {
      id: '/_authenticated/user/workspaces/'
      path: '/workspaces'
      fullPath: '/user/workspaces/'
      preLoaderRoute: typeof AuthenticatedUserWorkspacesPageRouteImport
      parentRoute: typeof AuthenticatedUserLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/': {
      id: '/_authenticated/workspaces/$workspaceId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/api-keys': {
      id: '/_authenticated/workspaces/$workspaceId/api-keys'
      path: '/api-keys'
      fullPath: '/workspaces/$workspaceId/api-keys'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/members': {
      id: '/_authenticated/workspaces/$workspaceId/members'
      path: '/members'
      fullPath: '/workspaces/$workspaceId/members'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRoute
    }
    '/_authenticated/workspaces/create/': {
      id: '/_authenticated/workspaces/create/'
      path: '/workspaces/create'
      fullPath: '/workspaces/create/'
      preLoaderRoute: typeof AuthenticatedWorkspacesCreatePageRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/admin/users/$userId/': {
      id: '/_authenticated/admin/users/$userId/'
      path: '/$userId'
      fullPath: '/admin/users/$userId/'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdPageRouteImport
      parentRoute: typeof AuthenticatedAdminUsersLayoutRoute
    }
    '/_authenticated/admin/users/create/': {
      id: '/_authenticated/admin/users/create/'
      path: '/create'
      fullPath: '/admin/users/create/'
      preLoaderRoute: typeof AuthenticatedAdminUsersCreatePageRouteImport
      parentRoute: typeof AuthenticatedAdminUsersLayoutRoute
    }
    '/_authenticated/user/api-keys/$apiKeyId/': {
      id: '/_authenticated/user/api-keys/$apiKeyId/'
      path: '/$apiKeyId'
      fullPath: '/user/api-keys/$apiKeyId/'
      preLoaderRoute: typeof AuthenticatedUserApiKeysApiKeyIdPageRouteImport
      parentRoute: typeof AuthenticatedUserApiKeysLayoutRoute
    }
    '/_authenticated/user/api-keys/create/': {
      id: '/_authenticated/user/api-keys/create/'
      path: '/create'
      fullPath: '/user/api-keys/create/'
      preLoaderRoute: typeof AuthenticatedUserApiKeysCreatePageRouteImport
      parentRoute: typeof AuthenticatedUserApiKeysLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/api-keys/': {
      id: '/_authenticated/workspaces/$workspaceId/api-keys/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/api-keys/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/members/': {
      id: '/_authenticated/workspaces/$workspaceId/members/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/members/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/settings/': {
      id: '/_authenticated/workspaces/$workspaceId/settings/'
      path: '/settings'
      fullPath: '/workspaces/$workspaceId/settings/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdSettingsPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/api-keys/$apiKeyId/': {
      id: '/_authenticated/workspaces/$workspaceId/api-keys/$apiKeyId/'
      path: '/$apiKeyId'
      fullPath: '/workspaces/$workspaceId/api-keys/$apiKeyId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysApiKeyIdPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/api-keys/create/': {
      id: '/_authenticated/workspaces/$workspaceId/api-keys/create/'
      path: '/create'
      fullPath: '/workspaces/$workspaceId/api-keys/create/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysCreatePageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/members/$memberId/': {
      id: '/_authenticated/workspaces/$workspaceId/members/$memberId/'
      path: '/$memberId'
      fullPath: '/workspaces/$workspaceId/members/$memberId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute
    }
    '/_authenticated/workspaces/$workspaceId/members/invite/': {
      id: '/_authenticated/workspaces/$workspaceId/members/invite/'
      path: '/invite'
      fullPath: '/workspaces/$workspaceId/members/invite/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersInvitePageRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute
    }
  }
}

interface AuthenticatedAdminUsersLayoutRouteChildren {
  AuthenticatedAdminUsersPageRoute: typeof AuthenticatedAdminUsersPageRoute
  AuthenticatedAdminUsersUserIdPageRoute: typeof AuthenticatedAdminUsersUserIdPageRoute
  AuthenticatedAdminUsersCreatePageRoute: typeof AuthenticatedAdminUsersCreatePageRoute
}

const AuthenticatedAdminUsersLayoutRouteChildren: AuthenticatedAdminUsersLayoutRouteChildren =
  {
    AuthenticatedAdminUsersPageRoute: AuthenticatedAdminUsersPageRoute,
    AuthenticatedAdminUsersUserIdPageRoute:
      AuthenticatedAdminUsersUserIdPageRoute,
    AuthenticatedAdminUsersCreatePageRoute:
      AuthenticatedAdminUsersCreatePageRoute,
  }

const AuthenticatedAdminUsersLayoutRouteWithChildren =
  AuthenticatedAdminUsersLayoutRoute._addFileChildren(
    AuthenticatedAdminUsersLayoutRouteChildren,
  )

interface AuthenticatedAdminLayoutRouteChildren {
  AuthenticatedAdminUsersLayoutRoute: typeof AuthenticatedAdminUsersLayoutRouteWithChildren
  AuthenticatedAdminPageRoute: typeof AuthenticatedAdminPageRoute
}

const AuthenticatedAdminLayoutRouteChildren: AuthenticatedAdminLayoutRouteChildren =
  {
    AuthenticatedAdminUsersLayoutRoute:
      AuthenticatedAdminUsersLayoutRouteWithChildren,
    AuthenticatedAdminPageRoute: AuthenticatedAdminPageRoute,
  }

const AuthenticatedAdminLayoutRouteWithChildren =
  AuthenticatedAdminLayoutRoute._addFileChildren(
    AuthenticatedAdminLayoutRouteChildren,
  )

interface AuthenticatedUserApiKeysLayoutRouteChildren {
  AuthenticatedUserApiKeysPageRoute: typeof AuthenticatedUserApiKeysPageRoute
  AuthenticatedUserApiKeysApiKeyIdPageRoute: typeof AuthenticatedUserApiKeysApiKeyIdPageRoute
  AuthenticatedUserApiKeysCreatePageRoute: typeof AuthenticatedUserApiKeysCreatePageRoute
}

const AuthenticatedUserApiKeysLayoutRouteChildren: AuthenticatedUserApiKeysLayoutRouteChildren =
  {
    AuthenticatedUserApiKeysPageRoute: AuthenticatedUserApiKeysPageRoute,
    AuthenticatedUserApiKeysApiKeyIdPageRoute:
      AuthenticatedUserApiKeysApiKeyIdPageRoute,
    AuthenticatedUserApiKeysCreatePageRoute:
      AuthenticatedUserApiKeysCreatePageRoute,
  }

const AuthenticatedUserApiKeysLayoutRouteWithChildren =
  AuthenticatedUserApiKeysLayoutRoute._addFileChildren(
    AuthenticatedUserApiKeysLayoutRouteChildren,
  )

interface AuthenticatedUserLayoutRouteChildren {
  AuthenticatedUserApiKeysLayoutRoute: typeof AuthenticatedUserApiKeysLayoutRouteWithChildren
  AuthenticatedUserPageRoute: typeof AuthenticatedUserPageRoute
  AuthenticatedUserSecurityPageRoute: typeof AuthenticatedUserSecurityPageRoute
  AuthenticatedUserWorkspacesPageRoute: typeof AuthenticatedUserWorkspacesPageRoute
}

const AuthenticatedUserLayoutRouteChildren: AuthenticatedUserLayoutRouteChildren =
  {
    AuthenticatedUserApiKeysLayoutRoute:
      AuthenticatedUserApiKeysLayoutRouteWithChildren,
    AuthenticatedUserPageRoute: AuthenticatedUserPageRoute,
    AuthenticatedUserSecurityPageRoute: AuthenticatedUserSecurityPageRoute,
    AuthenticatedUserWorkspacesPageRoute: AuthenticatedUserWorkspacesPageRoute,
  }

const AuthenticatedUserLayoutRouteWithChildren =
  AuthenticatedUserLayoutRoute._addFileChildren(
    AuthenticatedUserLayoutRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute
  AuthenticatedWorkspacesWorkspaceIdApiKeysApiKeyIdPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysApiKeyIdPageRoute
  AuthenticatedWorkspacesWorkspaceIdApiKeysCreatePageRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysCreatePageRoute
}

const AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute:
      AuthenticatedWorkspacesWorkspaceIdApiKeysPageRoute,
    AuthenticatedWorkspacesWorkspaceIdApiKeysApiKeyIdPageRoute:
      AuthenticatedWorkspacesWorkspaceIdApiKeysApiKeyIdPageRoute,
    AuthenticatedWorkspacesWorkspaceIdApiKeysCreatePageRoute:
      AuthenticatedWorkspacesWorkspaceIdApiKeysCreatePageRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdMembersPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersPageRoute
  AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute
  AuthenticatedWorkspacesWorkspaceIdMembersInvitePageRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersInvitePageRoute
}

const AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdMembersPageRoute:
      AuthenticatedWorkspacesWorkspaceIdMembersPageRoute,
    AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute:
      AuthenticatedWorkspacesWorkspaceIdMembersMemberIdPageRoute,
    AuthenticatedWorkspacesWorkspaceIdMembersInvitePageRoute:
      AuthenticatedWorkspacesWorkspaceIdMembersInvitePageRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceIdLayoutRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteWithChildren
  AuthenticatedWorkspacesWorkspaceIdPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdPageRoute
  AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute: typeof AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute
}

const AuthenticatedWorkspacesWorkspaceIdLayoutRouteChildren: AuthenticatedWorkspacesWorkspaceIdLayoutRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRoute:
      AuthenticatedWorkspacesWorkspaceIdApiKeysLayoutRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdMembersLayoutRoute:
      AuthenticatedWorkspacesWorkspaceIdMembersLayoutRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceIdPageRoute:
      AuthenticatedWorkspacesWorkspaceIdPageRoute,
    AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute:
      AuthenticatedWorkspacesWorkspaceIdSettingsPageRoute,
  }

const AuthenticatedWorkspacesWorkspaceIdLayoutRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceIdLayoutRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceIdLayoutRouteChildren,
  )

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedAdminLayoutRoute: typeof AuthenticatedAdminLayoutRouteWithChildren
  AuthenticatedUserLayoutRoute: typeof AuthenticatedUserLayoutRouteWithChildren
  AuthenticatedPageRoute: typeof AuthenticatedPageRoute
  AuthenticatedWorkspacesWorkspaceIdLayoutRoute: typeof AuthenticatedWorkspacesWorkspaceIdLayoutRouteWithChildren
  AuthenticatedWorkspacesPageRoute: typeof AuthenticatedWorkspacesPageRoute
  AuthenticatedWorkspacesCreatePageRoute: typeof AuthenticatedWorkspacesCreatePageRoute
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedAdminLayoutRoute: AuthenticatedAdminLayoutRouteWithChildren,
  AuthenticatedUserLayoutRoute: AuthenticatedUserLayoutRouteWithChildren,
  AuthenticatedPageRoute: AuthenticatedPageRoute,
  AuthenticatedWorkspacesWorkspaceIdLayoutRoute:
    AuthenticatedWorkspacesWorkspaceIdLayoutRouteWithChildren,
  AuthenticatedWorkspacesPageRoute: AuthenticatedWorkspacesPageRoute,
  AuthenticatedWorkspacesCreatePageRoute:
    AuthenticatedWorkspacesCreatePageRoute,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

interface AuthLayoutRouteChildren {
  AuthForgotPasswordPageRoute: typeof AuthForgotPasswordPageRoute
  AuthLoginPageRoute: typeof AuthLoginPageRoute
  AuthRegisterPageRoute: typeof AuthRegisterPageRoute
  AuthResetPasswordPageRoute: typeof AuthResetPasswordPageRoute
  AuthVerifyEmailPageRoute: typeof AuthVerifyEmailPageRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthForgotPasswordPageRoute: AuthForgotPasswordPageRoute,
  AuthLoginPageRoute: AuthLoginPageRoute,
  AuthRegisterPageRoute: AuthRegisterPageRoute,
  AuthResetPasswordPageRoute: AuthResetPasswordPageRoute,
  AuthVerifyEmailPageRoute: AuthVerifyEmailPageRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  InvitePageRoute: InvitePageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
