import type { FilterQuery, FindOptions } from "@mikro-orm/core";
import { SqlEntityManager } from "@mikro-orm/sql";
import { Injectable } from "@nestjs/common";
import type { GraphQLResolveInfo } from "graphql";

import { ConnectionQueryBuilder } from "./connection-query-builder.js";
import {
  ConnectionArgsInterface,
  ConnectionInterface,
  ConnectionResult,
} from "./interfaces/index.js";
import { ConnectionClass } from "./types/index.js";
import { isConnectionTotalCountSelected } from "./utils/is-connection-total-count-selected.js";

/**
 * Options for the ConnectionManager.find method.
 *
 * Extends MikroORM FindOptions but excludes pagination-related options
 * (limit, offset, orderBy) which are handled by the connection arguments.
 *
 * @typeParam Entity - The entity type being queried
 * @typeParam Hint - Type hints for population
 * @typeParam Fields - Fields to select
 * @typeParam Excludes - Fields to exclude
 */
export interface ConnectionFindOptions<
  Entity extends object,
  Hint extends string = never,
  Fields extends string = "*",
  Excludes extends string = never,
> extends Omit<
  FindOptions<Entity, Hint, Fields, Excludes>,
  "limit" | "offset" | "orderBy"
> {
  /**
   * Additional filter query to apply to the connection query.
   * This is merged with any filters from the connection arguments.
   */
  where?: FilterQuery<Entity>;
}

/**
 * Selection-aware options for the ConnectionManager.find method.
 *
 * @typeParam Entity - The entity type being queried
 * @typeParam Hint - Type hints for population
 * @typeParam Fields - Fields to select
 * @typeParam Excludes - Fields to exclude
 */
export interface ConnectionSelectionFindOptions<
  Entity extends object,
  Hint extends string = never,
  Fields extends string = "*",
  Excludes extends string = never,
> extends ConnectionFindOptions<Entity, Hint, Fields, Excludes> {
  /**
   * GraphQL resolver information used to avoid querying connection counts when
   * neither `totalCount` nor `totalCountRelation` is selected.
   *
   * Pass the value provided by NestJS GraphQL's `@Info()` decorator. When
   * neither field is selected, the unselected count properties are omitted
   * from the resolver source object.
   */
  info: GraphQLResolveInfo;
}

/**
 * Service for executing paginated GraphQL connection queries.
 *
 * The ConnectionManager provides a high-level API for querying entities
 * with cursor-based pagination following the Relay connection specification.
 *
 * @example Basic usage in a resolver
 * ```typescript
 * @Resolver(() => User)
 * export class UserResolver {
 *   constructor(private readonly connectionManager: ConnectionManager) {}
 *
 *   @Query(() => UserConnection)
 *   async users(
 *     @Args() args: UserConnectionArgs,
 *     @Info() info: GraphQLResolveInfo,
 *   ): Promise<ConnectionResult<User>> {
 *     return this.connectionManager.find(UserConnection, args, { info });
 *   }
 * }
 * ```
 *
 * @example With additional filters
 * ```typescript
 * @Query(() => UserConnection)
 * async activeUsers(@Args() args: UserConnectionArgs): Promise<UserConnection> {
 *   return this.connectionManager.find(UserConnection, args, {
 *     where: { isActive: true },
 *   });
 * }
 * ```
 */
@Injectable()
export class ConnectionManager {
  /** Creates a new ConnectionManager instance.
   * @param em - MikroORM SQL entity manager for querying entities
   */
  constructor(private readonly em: SqlEntityManager) {}

  /**
   * Finds entities and returns them as a paginated connection.
   *
   * @typeParam Entity - The entity type being queried
   * @typeParam Hint - Type hints for population
   * @typeParam Fields - Fields to select
   * @typeParam Excludes - Fields to exclude
   * @param connectionClass - The connection class generated by ConnectionBuilder
   * @param args - The connection arguments (first, last, after, before, orderBy, filter, query)
   * @param options - Additional find options (where, populate, etc.)
   * @returns A promise that resolves to the paginated connection result
   */
  async find<
    Entity extends object,
    Hint extends string = never,
    Fields extends string = "*",
    Excludes extends string = never,
  >(
    connectionClass: ConnectionClass<Entity>,
    args: ConnectionArgsInterface<Entity>,
    options: ConnectionSelectionFindOptions<Entity, Hint, Fields, Excludes>,
  ): Promise<ConnectionResult<Entity>>;

  async find<
    Entity extends object,
    Hint extends string = never,
    Fields extends string = "*",
    Excludes extends string = never,
  >(
    connectionClass: ConnectionClass<Entity>,
    args: ConnectionArgsInterface<Entity>,
    options?: ConnectionFindOptions<Entity, Hint, Fields, Excludes>,
  ): Promise<ConnectionInterface<Entity>>;

  async find<
    Entity extends object,
    Hint extends string = never,
    Fields extends string = "*",
    Excludes extends string = never,
  >(
    connectionClass: ConnectionClass<Entity>,
    args: ConnectionArgsInterface<Entity>,
    options?:
      | ConnectionFindOptions<Entity, Hint, Fields, Excludes>
      | ConnectionSelectionFindOptions<Entity, Hint, Fields, Excludes>,
  ): Promise<ConnectionResult<Entity>> {
    let info: GraphQLResolveInfo | undefined;
    let findOptions:
      | ConnectionFindOptions<Entity, Hint, Fields, Excludes>
      | undefined;

    if (typeof options !== "undefined" && "info" in options) {
      const { info: resolveInfo, ...databaseFindOptions } = options;
      info = resolveInfo;
      findOptions = databaseFindOptions;
    } else {
      findOptions = options;
    }

    const includeTotalCount =
      typeof info === "undefined" || isConnectionTotalCountSelected(info);

    return await new ConnectionQueryBuilder(
      this.em,
      connectionClass,
      args,
      findOptions,
      includeTotalCount,
    ).query();
  }
}
