import { EntityManager, type FilterQuery } from "@mikro-orm/core";
import type { FindOptions } from "@mikro-orm/core/drivers";
import { Injectable } from "@nestjs/common";

import { ConnectionQueryBuilder } from "./connection-query-builder";
import { ConnectionArgsInterface, ConnectionInterface } from "./interfaces";
import { ConnectionClass } from "./types";

/**
 * Options for the ConnectionManager.find method.
 *
 * Extends MikroORM FindOptions but excludes pagination-related options
 * (limit, offset, orderBy) which are handled by the connection arguments.
 *
 * @typeParam Entity - The entity type being queried
 * @typeParam Hint - Type hints for population
 * @typeParam Fields - Fields to select
 * @typeParam Excludes - Fields to exclude
 */
export interface ConnectionFindOptions<
  Entity extends object,
  Hint extends string = never,
  Fields extends string = "*",
  Excludes extends string = never,
> extends Exclude<
  FindOptions<Entity, Hint, Fields, Excludes>,
  "limit" | "offset" | "orderBy"
> {
  /**
   * Additional filter query to apply to the connection query.
   * This is merged with any filters from the connection arguments.
   */
  where?: FilterQuery<Entity>;
}

/**
 * Service for executing paginated GraphQL connection queries.
 *
 * The ConnectionManager provides a high-level API for querying entities
 * with cursor-based pagination following the Relay connection specification.
 *
 * @example Basic usage in a resolver
 * ```typescript
 * @Resolver(() => User)
 * export class UserResolver {
 *   constructor(private readonly connectionManager: ConnectionManager) {}
 *
 *   @Query(() => UserConnection)
 *   async users(@Args() args: UserConnectionArgs): Promise<UserConnection> {
 *     return this.connectionManager.find(UserConnection, args);
 *   }
 * }
 * ```
 *
 * @example With additional filters
 * ```typescript
 * @Query(() => UserConnection)
 * async activeUsers(@Args() args: UserConnectionArgs): Promise<UserConnection> {
 *   return this.connectionManager.find(UserConnection, args, {
 *     where: { isActive: true },
 *   });
 * }
 * ```
 */
@Injectable()
export class ConnectionManager {
  /** Creates a new ConnectionManager instance.
   * @param em - MikroORM entity manager for querying entities
   */
  constructor(private readonly em: EntityManager) {}

  /**
   * Finds entities and returns them as a paginated connection.
   *
   * @typeParam Entity - The entity type being queried
   * @typeParam Hint - Type hints for population
   * @typeParam Fields - Fields to select
   * @typeParam Excludes - Fields to exclude
   * @param connectionClass - The connection class generated by ConnectionBuilder
   * @param args - The connection arguments (first, last, after, before, orderBy, filter, query)
   * @param options - Additional find options (where, populate, etc.)
   * @returns A promise that resolves to the paginated connection result
   */
  async find<
    Entity extends object,
    Hint extends string = never,
    Fields extends string = "*",
    Excludes extends string = never,
  >(
    connectionClass: ConnectionClass<Entity>,
    args: ConnectionArgsInterface<Entity>,
    options?: ConnectionFindOptions<Entity, Hint, Fields, Excludes>,
  ): Promise<ConnectionInterface<Entity>> {
    return await new ConnectionQueryBuilder(
      this.em,
      connectionClass,
      args,
      options,
    ).query();
  }
}
