/** 用户管理与会话权限。 */
export enum UserPermission {
  /** 创建用户。 */
  USER_CREATE = 'user:create',
  /** 列出用户。 */
  USER_LIST = 'user:list',
  /** 设置用户角色。 */
  USER_SET_ROLE = 'user:set-role',
  /** 封禁用户。 */
  USER_BAN = 'user:ban',
  /** 模拟登录普通用户。 */
  USER_IMPERSONATE = 'user:impersonate',
  /** 模拟登录管理员。 */
  USER_IMPERSONATE_ADMINS = 'user:impersonate-admins',
  /** 删除用户。 */
  USER_DELETE = 'user:delete',
  /** 设置用户密码。 */
  USER_SET_PASSWORD = 'user:set-password',
  /** 设置用户邮箱。 */
  USER_SET_EMAIL = 'user:set-email',
  /** 获取用户。 */
  USER_GET = 'user:get',
  /** 更新用户。 */
  USER_UPDATE = 'user:update',
  /** 列出用户会话。 */
  SESSION_LIST = 'session:list',
  /** 撤销用户会话。 */
  SESSION_REVOKE = 'session:revoke',
  /** 删除用户会话。 */
  SESSION_DELETE = 'session:delete',
}
