name: Pull request

on:
  pull_request:
    branches:
      - master

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
